"""
Simulator — multi-agent tribe agent implementations.

Three agent types:

HonestAgent:
    Cooperates normally. Two backends:
    - "mock": scripted responses from scenario config (deterministic, Phase 0)
    - "ollama": calls local Ollama API (requires `ollama serve` + a pulled model)

MisalignedAgent:
    Honest until `bad_actor_start_turn`, then follows `bad_actor_script` template.
    Script = list of message templates; cycling through them from start_turn onward.
    This models the gradual drift pattern studied in the Conformity paper.

WhiteBoxAgent:
    Honest or misaligned, but also exposes simulated internal activations.
    Activations are generated by a small fixed MLP applied to the message embedding:
    - Honest agents: activation ≈ embed(message) projected through honest_direction
    - Misaligned agents: activation += bad_direction_vec (detectable by Part A)

All agents implement the same interface:
    agent.step(context: list[dict]) -> tuple[str, list[str]]
         returns (message_text, tool_calls)

    white_box_agent.get_activations() -> torch.Tensor   # [activation_dim]
"""

from __future__ import annotations

import json
import re
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import requests
import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Ollama client
# ---------------------------------------------------------------------------

class OllamaClient:
    """Thin wrapper around the Ollama local API."""

    DEFAULT_URL = "http://localhost:11434"

    def __init__(self, base_url: str = DEFAULT_URL, model: str = "llama3") -> None:
        self.base_url = base_url
        self.model    = model

    def complete(
        self,
        system:   str,
        messages: list[dict],   # [{"role": "user"/"assistant", "content": "..."}]
        timeout:  int = 30,
    ) -> str:
        """Call /api/chat and return the assistant's text reply."""
        payload = {
            "model":    self.model,
            "messages": [{"role": "system", "content": system}] + messages,
            "stream":   False,
        }
        try:
            resp = requests.post(
                f"{self.base_url}/api/chat",
                json=payload,
                timeout=timeout,
            )
            resp.raise_for_status()
            data = resp.json()
            return data["message"]["content"]
        except (requests.RequestException, KeyError, json.JSONDecodeError) as e:
            return f"[OllamaClient error: {e}]"

    def is_available(self) -> bool:
        try:
            resp = requests.get(f"{self.base_url}/api/tags", timeout=3)
            return resp.status_code == 200
        except requests.RequestException:
            return False


# ---------------------------------------------------------------------------
# Base agent
# ---------------------------------------------------------------------------

class BaseAgent(ABC):
    def __init__(self, agent_id: str, system_prompt: str) -> None:
        self.agent_id      = agent_id
        self.system_prompt = system_prompt
        self._turn         = 0

    @abstractmethod
    def step(self, context: list[dict]) -> tuple[str, list[str]]:
        """
        Produce a message for this turn.

        Args:
            context: list of {"agent_id": ..., "content": ..., "turn": ...}
                     representing the conversation history visible to this agent.
        Returns:
            (message_text, tool_calls)
        """
        ...

    def advance_turn(self) -> None:
        self._turn += 1

    @property
    def current_turn(self) -> int:
        return self._turn


# ---------------------------------------------------------------------------
# HonestAgent
# ---------------------------------------------------------------------------

class HonestAgent(BaseAgent):
    """
    Cooperative agent: tries to help with the task.

    Backend:
        "mock"   — returns messages from a scripted list (deterministic, no LLM)
        "ollama" — calls local Ollama for generated responses
    """

    def __init__(
        self,
        agent_id:      str,
        system_prompt: str,
        mock_messages: Optional[list[str]] = None,
        ollama_client: Optional[OllamaClient] = None,
    ) -> None:
        super().__init__(agent_id, system_prompt)
        self._mock_messages = mock_messages or []
        self._ollama        = ollama_client

    def step(self, context: list[dict]) -> tuple[str, list[str]]:
        msg = self._generate(context)
        self.advance_turn()
        return msg, []

    def _generate(self, context: list[dict]) -> str:
        # Ollama path
        if self._ollama is not None and self._ollama.is_available():
            messages = [
                {"role": "user" if m["agent_id"] != self.agent_id else "assistant",
                 "content": f"[{m['agent_id']}]: {m['content']}"}
                for m in context[-6:]   # last 6 turns for context window
            ]
            return self._ollama.complete(self.system_prompt, messages)

        # Mock path
        if self._mock_messages:
            idx = self._turn % len(self._mock_messages)
            return self._mock_messages[idx]

        # Bare fallback
        return f"[{self.agent_id}] Acknowledged. Proceeding with task."


# ---------------------------------------------------------------------------
# MisalignedAgent
# ---------------------------------------------------------------------------

class MisalignedAgent(BaseAgent):
    """
    Honest until bad_actor_start_turn, then switches to bad-actor mode.

    bad_actor_script: list of message templates.  Each template may contain
        {turn}    — current turn number
        {context} — summary of recent messages
    Cycles through the list from start_turn onward.
    """

    def __init__(
        self,
        agent_id:             str,
        system_prompt:        str,
        bad_actor_start_turn: int,
        bad_actor_script:     list[str],
        honest_mock_messages: Optional[list[str]] = None,
        ollama_client:        Optional[OllamaClient] = None,
    ) -> None:
        super().__init__(agent_id, system_prompt)
        self.bad_actor_start_turn = bad_actor_start_turn
        self.bad_actor_script     = bad_actor_script
        self._honest_agent        = HonestAgent(
            agent_id, system_prompt, honest_mock_messages, ollama_client
        )
        self._ollama = ollama_client

    @property
    def is_bad_actor_active(self) -> bool:
        return self._turn >= self.bad_actor_start_turn

    def step(self, context: list[dict]) -> tuple[str, list[str]]:
        if not self.is_bad_actor_active:
            msg, tools = self._honest_agent.step(context)
            self.advance_turn()
            return msg, tools

        # Bad actor mode
        script_idx = (self._turn - self.bad_actor_start_turn) % max(len(self.bad_actor_script), 1)
        template   = self.bad_actor_script[script_idx]

        context_summary = " | ".join(
            f"{m['agent_id']}: {m['content'][:60]}" for m in context[-3:]
        )

        # Use safe formatting: unknown keys (e.g. hex literals in YAML scripts) are kept as-is
        try:
            msg = template.format(
                turn     = self._turn,
                context  = context_summary,
                agent_id = self.agent_id,
            )
        except (KeyError, IndexError, ValueError):
            # Template contains unexpected placeholders (e.g. {0x...}); use as-is
            msg = template

        self.advance_turn()
        return msg, []


# ---------------------------------------------------------------------------
# WhiteBoxAgent — exposes simulated activations
# ---------------------------------------------------------------------------

_ACTIVATION_DIM = 128   # simulated activation dimension


class _HashEncoder:
    """
    Deterministic hash-based pseudo-encoder used when sentence_transformers
    is not installed. Produces consistent [output_dim] vectors for any string.
    Used only in tests and fallback environments.
    """
    def __init__(self, output_dim: int) -> None:
        self.output_dim = output_dim

    def encode(self, text: str, convert_to_tensor: bool = True) -> torch.Tensor:
        import hashlib
        h = hashlib.sha256(text.encode()).digest()
        # Repeat bytes to fill output_dim floats
        rng = np.random.RandomState(seed=int.from_bytes(h[:4], "little"))
        vec = rng.randn(self.output_dim).astype(np.float32)
        vec = torch.from_numpy(vec)
        return vec if convert_to_tensor else vec.numpy()

    def get_sentence_embedding_dimension(self) -> int:
        return self.output_dim



# Module-level ST model cache — loaded once per process, shared across all
# WhiteBoxAgent instances. Prevents per-agent HuggingFace API round-trips.
_WB_ST_CACHE: dict[str, object] = {}


class _ActivationMLP(nn.Module):
    """Small fixed MLP that converts message embedding → activation vector."""

    def __init__(self, input_dim: int, output_dim: int) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class WhiteBoxAgent:
    """
    Wraps HonestAgent or MisalignedAgent and additionally exposes a
    simulated activation tensor after each step().

    Activation model:
        z = MLP(embed(message))
        if misaligned and bad actor active:  z += bad_direction_vec

    The bad_direction_vec is a fixed unit vector in activation space — a different
    vector per attack family.  This gives Part A's SAE meaningful signal to detect.

    The MLP weights are randomly initialised but FIXED (no training) — they just
    provide a stable, nonlinear projection of message semantics.
    """

    def __init__(
        self,
        inner_agent,               # HonestAgent or MisalignedAgent
        bad_direction_vec:  Optional[np.ndarray] = None,  # [_ACTIVATION_DIM]
        drift_magnitude:    float = 2.0,
        sentence_model_name: str = "all-MiniLM-L6-v2",
    ) -> None:
        self._inner            = inner_agent
        self._last_activations: Optional[torch.Tensor] = None
        self._drift_magnitude  = drift_magnitude

        # Lazy-load sentence encoder
        self._st      = None
        self._st_name = sentence_model_name
        self._sent_dim: Optional[int] = None

        # Fixed MLP (not trained — just a stable projection)
        self._mlp: Optional[_ActivationMLP] = None

        # Bad direction: unique per attack family
        if bad_direction_vec is not None:
            bd = np.array(bad_direction_vec, dtype=np.float32)
            self._bad_dir = torch.from_numpy(bd / (np.linalg.norm(bd) + 1e-12))
        else:
            # Random fixed direction
            raw = torch.randn(_ACTIVATION_DIM)
            self._bad_dir = F.normalize(raw, dim=0)

    # --- public interface mirrors BaseAgent ---

    @property
    def agent_id(self) -> str:
        return self._inner.agent_id

    @property
    def current_turn(self) -> int:
        return self._inner.current_turn

    def step(self, context: list[dict]) -> tuple[str, list[str]]:
        msg, tools = self._inner.step(context)
        self._last_activations = self._compute_activations(msg)
        return msg, tools

    def get_activations(self) -> Optional[torch.Tensor]:
        """Returns [_ACTIVATION_DIM] simulated activation vector from last step."""
        return self._last_activations

    # --- internals ---

    def _get_st(self):
        """Lazy-load sentence encoder from module-level cache; one load per process."""
        global _WB_ST_CACHE
        key = self._st_name
        if key not in _WB_ST_CACHE:
            try:
                from sentence_transformers import SentenceTransformer
                st  = SentenceTransformer(key, device="cpu")   # CPU: MLP is always CPU
                dim = st.get_embedding_dimension()
                _WB_ST_CACHE[key] = (st, dim)
            except ImportError:
                _WB_ST_CACHE[key] = (_HashEncoder(_ACTIVATION_DIM), _ACTIVATION_DIM)
        cached_st, cached_dim = _WB_ST_CACHE[key]
        self._st       = cached_st
        self._sent_dim = cached_dim
        # Build (or rebuild) MLP if dim changed
        if self._mlp is None or self._mlp.net[0].in_features != self._sent_dim:
            self._mlp = _ActivationMLP(self._sent_dim, _ACTIVATION_DIM)
            for p in self._mlp.parameters():
                p.requires_grad = False
        return self._st


    @torch.no_grad()
    def _compute_activations(self, message: str) -> torch.Tensor:
        st  = self._get_st()
        emb = st.encode(message or "", convert_to_tensor=True)   # [sent_dim]
        if emb.dim() > 1:
            emb = emb.squeeze(0)
        act = self._mlp(emb.float())                             # [activation_dim]

        # Add misalignment drift if bad actor is active
        is_misaligned = (
            isinstance(self._inner, MisalignedAgent)
            and self._inner.is_bad_actor_active
        )
        if is_misaligned:
            act = act + self._drift_magnitude * self._bad_dir.to(act.device)

        return act
